{% set name = "gw_eccentricity" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gw_eccentricity-{{ version }}.tar.gz
  sha256: debf218b19d752feab06c1178740ea93f28e0637a53c07268811fb4f82610db9

build:
  script: |
      {{ PYTHON }} -m pip install . -vv
  number: 9
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - python-build
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - h5py
    - lalsuite
    - pylatexenc
    - sxs
    - scri
test:
  requires:
    - pip
  commands:
    - pip install polyrat
    - python -c "import gw_eccentricity"
    - pip check

about:
  home: https://github.com/vijayvarma392/gw_eccentricity
  summary: Defining eccentricity for gravitational wave astronomy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - md-arif-shaikh
    - vijayvarma392
