{% set name = "gw_eccentricity" %}
{% set version = "2.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gw_eccentricity-{{ version }}.tar.gz
  sha256: 070b736b314bb05b0cf1aae5dc4650c198c9bee81a13521d8aef3058e540a364

build:
  script: |
      {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - python-build
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - h5py
    - lalsuite
    - pylatexenc
    - sxs
    - scri
test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip install polyrat
    - pip install "bibtexparser>=2.0.0b8"
    - python -c "import gw_eccentricity"
    - pip check

about:
  home: https://github.com/vijayvarma392/gw_eccentricity
  summary: Defining eccentricity for gravitational wave astronomy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - md-arif-shaikh
    - vijayvarma392
