{% set name = "gw_eccentricity" %}
{% set version = "2.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gw_eccentricity-{{ version }}.tar.gz
  sha256: debf218b19d752feab06c1178740ea93f28e0637a53c07268811fb4f82610db9

build:
  script: |
      {{ PYTHON }} -m pip install . -vv
  number: 12
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - python-build
    - setuptools
    - build
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - h5py
    - lalsuite
    - pylatexenc
    - sxs
    - scri
test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip install polyrat
    - pip install "bibtexparser>=2.0.0b8"
    - python -c "import gw_eccentricity"
    - pip check

about:
  home: https://github.com/vijayvarma392/gw_eccentricity
  summary: Defining eccentricity for gravitational wave astronomy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - md-arif-shaikh
    - vijayvarma392
