{% set name = "gw_eccentricity" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gw_eccentricity-{{ version }}.tar.gz
  sha256: 61ca038be8b0a4bb98bdd86d0930d4d8e862b1d7232baa26990c684fbed0095c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - h5py
    - lalsuite
    - caltechdata-api
    - pylatexenc
    - sxs

test:
  imports:
    - gw_eccentricity
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vijayvarma392/gw_eccentricity
  summary: Defining eccentricity for gravitational wave astronomy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - md-arif-shaikh
    - vijayvarma392
