github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
extra:
  outputs:
    - gw_eccentricity
    - gw_eccentricity-postprocess
